### ISSUE TITLE
Hebrew holam not well aligned 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alerque/libertinus#107]
In the following text, the Hebrew holam does not change its position on Vav even if you inserted ZWNJ:
```
עֲוֹנֹת עֲו‌ֹנֹת 
```
![snapshot](https://i.imgur.com/rrXQ6Y3.png)

**Comment by khaledhosny** [comment]
Please give some context, I don’t know Hebrew at all.

**Comment by KrasnayaPloshchad** [comment]
I don’t know Hebrew too, but as my observe, the key of this problem is the sequence ו‌ֹ (vav + ZWNJ + holam), the ZWNJ could making holam shift to left, otherwise is shift to right.

**Comment by dscorbett** [comment]
The bug is that U+05B9 should be centered directly above U+05D5.

U+05B9 HEBREW POINT HOLAM is a vowel point above and to the left of its base letter. The exception is when the base letter is U+05D5 HEBREW LETTER VAV, where the holam goes directly above. However, the exception has exceptions; the holam above left on a vav is encoded as U+05BA HEBREW POINT HOLAM HASER FOR VAV. I don’t know what ZWNJ has to do with anything; maybe it was used as a workaround before U+05BA was encoded.

**Comment by KrasnayaPloshchad** [comment]
The text is copied from Wikipedia article [Zero-width non-joiner](https://en.wikipedia.org/wiki/Zero-width_non-joiner), the article explains that the placement of the holam dot to the left of the letter vav is correct in Biblical Hebrew, otherwise would resemble "seasons". However it does not mentioned any more technical purposes.

**Comment by mgavioli** [comment]
Can anybody with a working knowledge of Hebrew tell me if I am correct in assuming that:

1) The correct rendering of the U+05D5 + U+05B9 and of U+05D5 + U+05DA is as in the following screen shot (modified by hand from a LibreOffice screen shot by shifting slightly to the right the dot in the left-hand pair):

![issue_107_screenshot_01](https://user-images.githubusercontent.com/1420743/36414971-7d453034-1624-11e8-9a9d-2ad7183a8b59.png)

2) U+05D5 and U+05DA are the only diacritics which go **above** the HEBREW LETTER VAV.

If the answer to both points is yes, I think I can fix the issue (but I would probably lower a bit the diacritic in the U+05D5 + U+05B9 combination).

**Comment by alerque** [comment]
@dajare This sounds like something you might be able to answer.

**Comment by dajare** [comment]
[This looks good][1] to me. Just to spell out (as it were) the difference (with some simplifications):

- `U+05D5` is the "base" letter, [*waw*][w], which is a consonant, but commonly in biblical (Tiberian) Hebrew can also represent the [vowel "o"][o] (*holem*, the name of its over-dot sign);
- when *waw* is used **consonantally** with the mark (over-dot) for "o" (so the base + dot together = *wo*), then `U+05BA (Point Holam Haser for Vav)` is used with it, and the over-dot is shifted towards the left edge of the base *waw*;
- but when *waw* is used to represent a **vowel**, then the "*holem-waw*" combination (which also has a [precomposed representation at `U+FB4B`][p]) has the over-dot `U+05B9 Point Holam` centered over the base letter *waw* (and the base + dot together = *o*).

These scenarios are correctly displayed in @mgavioli comment above.

[p]: https://en.wikipedia.org/wiki/Holam#Computer_encoding
[o]: https://en.wikipedia.org/wiki/Holam
[w]: https://en.wikipedia.org/wiki/Waw_(letter)#Hebrew_Waw
[1]: https://github.com/khaledhosny/libertinus/issues/107#issuecomment-366911570

**Comment by dajare** [comment]
P.s. The form used by OP to diagnose this problem =  עֲוֹנֹת has a file on [Wikimedia Commons][w] showing the correct placement of the "over-dot" for `Holam Haser for Vav`:

![pic](https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Correct_Hebrew_Vav_with_Holam_haser_with_ZWNJ.svg/80px-Correct_Hebrew_Vav_with_Holam_haser_with_ZWNJ.svg.png)

This a case of "consonantal *waw*", and you can see the *holam* over the *waw* is "shifted" off to the left which is what `U+05BA` is supposed to do (*not* directly aligned over the *waw*). From my understanding, in fact, it's a little *too* far to the left, and @mgavioli's example above (on the left margin of the glyph -- if that's the right term here) is better.

[w]: https://commons.wikimedia.org/wiki/File:Correct_Hebrew_Vav_with_Holam_haser_with_ZWNJ.svg

**Comment by mgavioli** [comment]
@dajare : thanks for the details. I had a look and I found that Hebrew set-up in Libertinus (for sure inherited from Linux Libertine) is, also given my quite limited knowledge of Hebrew, rather unclear. Primarily:

1. it uses the same anchors used for Latin/Greek/Cyrillic, which allows for entertaining combinations like A + SEGOL or Gamma + QUBUTS..., notwithstanding that Hebrew diacritics and Latin/Greek/Cyrillic diacritics 'hang' on different sides;
1. it also uses the same anchor for all the diacritics on the same 'edge' of the base glyph; for instance HOLAM, HOLAM FOR VAV, RAFE, SHIN DOT and SIN DOT all use the same anchor;
1. some letters lack some (necessary?) anchor; for instance, VAV, ZAYIN, YOD, NUN and FINAL NUN lack the anchor for the 'top' diacritics; ALEPH, ZAYIN, YOD, FINAL NUN, TSADI and FINAL TSADI, SHIN, DOUBLE VAV, VAV YOD and DOUBLE YOD lack the anchor for the middle diacritic(s) (primarily DAGESH/MAPIQ).

The results are, to my eye, sub-optimal, and the details are difficult to understand, debug and improve;  for instance, this is the result of combining HOLAM with all the Hebrew letters for which the 'top' anchor is defined (screen shot from FontForge itself):

![issue_107_screenshot_02](https://user-images.githubusercontent.com/1420743/36569466-33546272-182e-11e8-945c-6385f295aeea.png)

To me, at least the position above DALET, HET, LAMED, SHIN and, if relevant, the double vowels looks dubious.

I see two possible approaches:

**A)** Either simply 'fix' the "holam / holam-for-waw over waw" issue, as described in the OP, fixing the two relevant anchor offsets within the current set-up; this would be rather quick and 'dirty'
 &nbsp; &nbsp; OR
**B)** try to rationalise the anchoring set-up for Hebrew with specialised anchors, in order to arrive at generally better results; this is going to take a while (and has to be repeated for each font) and I for one would surely need the help of someone like you, with a more deep knowledge of Hebrew writing and 'working'; I am also unsure of the real relevance of this font family for (advanced?) Hebrew usage.

Comments, anyone?

**Comment by dajare** [comment]
@mgavioli I've got some comments, but (just now) not much time, so....

1. THANK YOU for looking into this. That's a lot of work, it's appreciated.

1. The absolute **worst** of the cases your graphic captures is LAMED. The others are passable (well, SHIN is dodgy), but LAMED is just plain *wrong* the HOLAM should be on the **left** of the upright stroke, not the right.

1. The five final forms *never* appear with HOLAM (it is linguistically impossible), so they don't need an "anchor" (if that's the right language), let alone have one fixed.

1. On your **A/B** alternative scenarios: A makes more sense to me, as anyone doing "advance" Hebrew usage will surely use [SBL Hebrew][s] which is "industry standard". Except that...

1. ... It might be possible to use SBL Hebrew's "layout engine" (?) in Libertinus. The [Culmus Project][c] has produced a number of [Hebrew fonts][t] with [vowels][v] and [accents/cantillation][a] using the "layout logic" for the accents from SBL Hebrew (from the Culmus Project landing page):

    > Hebrew cantillation marks OpenType layout logic copyright (c) 2003 & 2007, Ralph Hancock and John Hudson. This layout logic for Biblical Hebrew is open source software under the MIT License; for details contact copyright holders at [Tiro][o].

    I don't know quite what this means for "fixing" these placement issues with Hebrew vowels (and [accents][i]) in Libertinus, but I thought it was worth mentioning.

I hope that helps for the moment. If I have other thoughts worth sharing, I'll be back! ;)

[o]: mailto:license%28at%29tiro.com
[a]: https://en.wikipedia.org/wiki/Cantillation#Names_and_shapes_of_the_te'amim
[v]: https://en.wikipedia.org/wiki/Niqqud
[s]: https://www.sbl-site.org/educational/BiblicalFonts_SBLHebrew.aspx
[c]: http://culmus.sourceforge.net/index.html
[t]: http://culmus.sourceforge.net/taamim/index.html
[i]: https://github.com/khaledhosny/libertinus/issues/106

**Comment by newgraph** [comment]
Hi!
It is possible to contextually place the HOLAM on the VAV only if it's supposed to be in the middle!

Here is a screenshot of the font I'm working on:

1]
<img width="541" alt="screenshot 2018-02-27 08 37 55" src="https://user-images.githubusercontent.com/36875437/36714141-961ce55a-1b99-11e8-9cf9-81c0c72fe081.png">
This is how it is when the VAV itself is pronounced.

2]
<img width="537" alt="screenshot 2018-02-27 08 38 07" src="https://user-images.githubusercontent.com/36875437/36714173-bfae5278-1b99-11e8-9b45-cdfec658d987.png">
This is how it is when the VAV itself is **not** pronounced, just used as a vowel for the preceding letter.

And best of all, it happens automatically as you type! (with the power of OpenType)

**Comment by mgavioli** [comment]
@dajare : thanks for your detailed comments; they have already some guide lines which can be used. While the possibility to re-use some already existing logic is interesting, it is anyway a fair amount of work (including 'clerical' work like contacting copyright holder and so on). I do not think I have the competences and the expertise to undertake such a task as 're-wiring' the Hebrew section from scratch.

Right now, I am dedicating the little spare time I have for these things to a much 'mundane' fix for the Latin part of the fonts. Once this is done, I'll see if if there is way to optimise the amount of work required and the generality of the result.

@newgraph : thanks for the post and the suggestion. I would say there is a contextual substitution based on the presence of a vowel mark on the preceding consonant, correct?

`<vovel> + VAV + HOLAM => HOLAM_FOR_VAV`

This seems an interesting solution, but I am sure there are caveats and traps the uninformed designed may easily fall into! Possibly I'll start with a 'simpler' solution...

**Comment by newgraph** [comment]
> I would say there is a contextual substitution based on the presence of a vowel mark on the preceding consonant, correct?

@mgavioli Correct!!!
This will **always** be correct with no exception!

If there is no **vowel mark** on the preceding letter it will always be a HOLAM MALEH [the dot on top-middle of the VAV].

Just keep in mind that I meant **vowel** mark, not **cantillation** mark.

**Comment by mgavioli** [comment]
@newgraph : sounds great!

Of course, HOLAM FOR VAV (U+5BA) shall still work correctly in its own, to cope with texts using it.

> Just keep in mind that I meant **vowel** mark, not **cantillation** mark.

Sure. Which makes for interesting fine points, as I think cantillation marks can occur between the preceding vowel and the VAV...

**Comment by newgraph** [comment]
This is my contextual positioning code [takes into account any possibility (I hope...)]:
```
lookup vavHolam {
lookupflag RightToLeft;
script hebr;

pos @anyLetter vav holam' <300 -30 0 0>;
pos @anyLetter [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] vav holam' <300 -30 0 0>;
pos @anyLetter [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] vav holam' <300 -30 0 0>;
pos @anyLetter [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] vav holam' <300 -30 0 0>;
pos @anyLetter vav [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] holam' <300 -30 0 0>;
pos @anyLetter vav [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] [shindot etnahta segolta shalshelet zaqefqatan zaqefgadol tipehaleft reviamugrash zarqa pashta yetiv tevirleft gereshaccent gereshmuqdam gershayimaccent qarneypara telishagedola pazer munahleft mahapakhleft merkhaleft merkhakefulaleft dargaleft qadma telishaqetana yerahbenyomoleft ole iluy dehi zinor masoracircle dagesh siluqleft rafe sindot] holam' <300 -30 0 0>;

} vavHolam;
```

**Comment by dscorbett** [comment]
This contextual positioning is inappropriate. In Unicode, a vav with U+05B9 is always a holam male. Adding automatic typo-correction to a font makes documents produced with it incompatible with other fonts.

**Comment by newgraph** [comment]
Correct, U+05B9 is always a holy male.

But the fact is [from my experience] that most texts are always typed with U+05B9 holam, and people don't use [or don't have the nerves to use] the second holam.

So the above is an excellent automatic solution for that!!!

But of course the other holam is still set to work, in order to be compatible with older texts...

**Comment by KrasnayaPloshchad** [comment]
SIL also published some documentations about Ezra SIL, they could be helpful for this.
https://scripts.sil.org/cms/scripts/page.php?item_id=SILHebrUni_Documentation

**Comment by khaledhosny** [comment]
Someone who knows Hebrew needs to fix this.
