### ISSUE TITLE
Can't output a correct PDF result in Math font

### ISSUE THREAD

**Issue by MarcusHKST** [alerque/libertinus#343]
hi all,
I am not sure if this is a problem of the Math font but I try to ask mention this.
I tried to use the MS Word 2016 to save some equations as PDF but some brackets are missing in the output. 

![image](https://user-images.githubusercontent.com/69705522/90304540-8f3c5c80-deeb-11ea-9781-3afbd1104bea.png)

**Comment by alerque** [comment]
I believe this is a function of the *very* buggy support of OTF fonts in MS Word. Libertines is currently distributed only in OTF format as it's what has the most features, works best most places, and has been verified. See also #326.

It isn't that hard to convert to TTF and that will get you past at least *some* of the Microsoft bugs, but you may loose other font features in the process. I will look into generating TTF automatically at some point when #334 is done, but if it doesn't live up to the quality of the OTF variant I won't be distributing it by default.

Please also complain to Microsoft. There is no excuse for such a corporation to charge such money for product leaving some blatant known issues untouched for years and expect everybody else to work around them.

**Comment by alerque** [comment]
Forgot to mention — since this comes down to a PDF export bug another way you can work around this is by using one of many PDF virtual printer drivers (including Open Source ones) that handle OTF fonts properly instead of using Microsoft's built in PDF export.

**Comment by MarcusHKST** [comment]
Oh! If this is the problem of Microsoft, I won't expect it will be fixed. Its famous 20-year print bug still exists!(Those who use it everyday may notice that)
