### ISSUE TITLE
Some mathematical glyphs are out of style

### ISSUE THREAD

**Issue by philosaurus** [alerque/libertinus#346]
U+2200, U+2201, U+2203 and U+2204 look like they're from another font. They are way thicker than other symbols (60+ em vs the regular 50) and their style is completely different to the rest.

![libertinus-math-out-of-style-glyphs](https://user-images.githubusercontent.com/18381707/90536324-31727380-e17c-11ea-893f-c9eac36eb7d2.png)

**Comment by khaledhosny** [comment]
That is by nature of these symbols, check them in other math fonts (Computer Modern/Latin Modern, or Cambria for instance)

**Comment by philosaurus** [comment]
To me they look small and "insignificant", even when compared to the other fonts mentioned. Cambria is close, but still seems a bit more prononced. They also look a little heavier than the other operators.
![quantifiers](https://user-images.githubusercontent.com/18381707/90554693-8b803280-e196-11ea-9293-cf0dff71bd21.png)

**Comment by Bolpat** [comment]
I changed the writing style (text *for all* versus ∀) because I so much dislike how the quantifiers look in Libertinus. They really should have the height of capital letters.

**Comment by ivo-s** [comment]
Hey @philosaurus and @Bolpat, see #454 for dicussion about resolving this issue.
