### ISSUE TITLE
Some operators have wrong sizing and alignment

### ISSUE THREAD

**Issue by philosaurus** [alerque/libertinus#347]
U+221F, U+2227–U+222A and U+228C–U+228E are placed on the baseline rather than being centered on the math axis. They also seem to be a bit small. The U+2229 and U+222A should probably be more similar in appearance to a rotated U+2282.

The + and × are only included in the image for reference.
![operators_wrong_size_placement](https://user-images.githubusercontent.com/18381707/90537565-c3c74700-e17d-11ea-883e-b657b37346dd.png)

**Comment by khaledhosny** [comment]
It is always good idea to check what other math fonts are doing here and what happens when the math font is used by a math layout engine (*TeX math mode, for example).

**Comment by philosaurus** [comment]
It's the same in XeTeX and Word. All other maths fonts I have are correctly aligned, so are other symbols in Libertinus.

**Comment by alerque** [comment]
Note to self or anybody else that works on this: while checking math symbol alignment also review whether `+lnum` vs. `+onum` features do/should affect what center line is used. See example [this comment on Elstob](https://github.com/psb1558/Elstob-font/issues/15#issuecomment-679868860).

**Comment by alerque** [comment]
Clearly @thlinard is somebody to ping to review alignment when a PR is ready for this :wink:!

**Comment by ivo-s** [comment]
Hey @philosaurus, see #454 for dicussion about resolving this issue. I am also pinging @thlinard concerning the alignment discussion in the same place.
