### ISSUE TITLE
Add slanted integrals

### ISSUE THREAD

**Issue by Dothion** [alerque/libertinus#357]
There is only upright integrals in this font. Could you please add slanted integrals as an option?

**Comment by alerque** [comment]
I'd be happy to consider this. Unfortunately math typesetting isn't an expertise of mine, so I'm going to need help. Either somebody needs to contribute the glyphs directly (which this project is open too) or at the very least if I'm ever going to do it myself I'm going to need some help tracking down other example fonts where these are used well, and also a document of some sort (preferable TeX) in which to test any changes in context where they would actually be used to see how well they work.

Are either of those things you can help with?

**Comment by RGB-es** [comment]
I cannot help either, but for inspiration you can look at STIX Two Math: it uses a slanted integral sign by default, but can switch to an upright symbol with a stylistic set (+ss08). Maybe you can go the opposite direction, using the upright integral as default and providing the slanted version as an stylistic set.

**Comment by alerque** [comment]
Thank @RGB-es. Can you provide a sample in anything that I can use for testing? Even a LibreOffice document with a formula showing STIX Two Math vs. Libertinus Math would help point me on the right trail to the right glyph(s)! Aren't integrals one of the math components that can be different sizes to span lines as well?

**Comment by RGB-es** [comment]
I created a file in LyX using XeTeX as backend. Here's the generated code

`
\documentclass[spanish]{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\setmainfont[Mapping=tex-text]{Libertinus Serif}
\setsansfont[Mapping=tex-text]{Libertinus Sans}
\setmonofont{Libertinus Mono}
\usepackage{esint}

\makeatletter
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% User specified LaTeX commands.
\setmathfont{Libertinus Math}

\makeatother

\usepackage{polyglossia}
\setdefaultlanguage{spanish}
\begin{document}
Libertinus Math:

\[
\int\limits _{a}^{b}f(x)dx=f(b)-f(a)
\]

STIX Two (default): {\setmathfont{STIX Two Math}

\[
\int\limits _{a}^{b}f(x)dx=f(b)-f(a)
\]

}

STIX Two (+ss08): {\setmathfont{STIX Two Math}[RawFeature={+ss08}]

\[
\int\limits _{a}^{b}f(x)dx=f(b)-f(a)
\]

}
\end{document}
`

![SeveralMathFonts](https://user-images.githubusercontent.com/7756783/91895474-97d8b500-ec97-11ea-87a4-023fd159be44.png)

**Comment by alerque** [comment]
Perfect, thanks. That's something to work from for myself (or anybody else) working on a new glyph option. And yes given the significant style change making this part of a stylistic alternate set will be the way to go.

**Comment by KrasnayaPloshchad** [comment]
Wikipedia is documented two types of slanted intrgrals.
See: https://en.wikipedia.org/wiki/Integral_symbol

**Comment by ivo-s** [comment]
I have a branch ready for a PR, but another PR #417 is pending. I don't know if issuing a PR based on another PR is a good idea. If I rebase it on the current master, the two PRs would have merge conflicts. I guess I'll wait for @alerque to handle #417 first and then submit it.
![image](https://user-images.githubusercontent.com/7095181/103431774-fd04ce80-4bd5-11eb-8bd0-eecd432d70fd.png)

**Comment by waldyrious** [comment]
I'm not a font designer, nor a mathematician, but for what it's worth, I thought I'd mention that the alignment of the limits in the slanted version seems a bit off to my eyes. I'd expect the b to be a little more to the right, and the a to be a little more to the left.

Perhaps this image illustrates better what my eyes find "misaligned":

![103431774-fd04ce80-4bd5-11eb-8bd0-eecd432d70fd](https://user-images.githubusercontent.com/478237/103437525-8e992e00-4c20-11eb-8d01-7f74eb272cac.png)

**Comment by ivo-s** [comment]
You are right, but to my knowledge, such fine positioning is not possible. I planned on a detailed explanation in the PR, but as you're bringing it up, let's address it here.

The way this positioning works in OTF is using italic correction. Source: https://docs.microsoft.com/en-us/typography/opentype/spec/math
From what I've gathered by testing, when typesetting these operator glyphs, italic correction is ignored in the normal sense. It is used to shift the limits in two ways. For `\limits`, both limits are shifted by 1/2 of italic correction in their respective directions. For `\nolimits`, the upper limit is typeset right after the right bearing, while the lower limit is shifted by italic correction. This way, the positioning of the limits is not independent for the two cases. The main limiting factor here is so the lower index does not collide with the integral, which I tested with the glyph `W`. This puts an upper limit on the italic correction. That is why the alignment is not optimal when switching to `\limits`, which can also be seen in other fonts.

[int_W.pdf](https://github.com/alerque/libertinus/files/5758915/int_W.pdf)

A special case are the inline path integrals, where the ring and arrow collide with the lower index for `\nolimits`. In my opinion, this case clearly has more priority in inline math than `\limits`, so I reduced the italic correction even more. Example:

[ointctrclockwise_W.pdf](https://github.com/alerque/libertinus/files/5758940/ointctrclockwise_W.pdf)

As you can see, even Latin Modern and STIX have problems with typesetting the limits. Anyway, feel free to examine various options using the following resources. If you use TeX Live and have `libertinus-fonts`, you can copy the font file below into `texmf-local/fonts/opentype/public/libertinus-fonts` and produce the output with XeLaTeX.
[LibertinusMath-Regular.otf.zip](https://github.com/alerque/libertinus/files/5758942/LibertinusMath-Regular.otf.zip)
```
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\setmainfont[Mapping=tex-text]{Libertinus Serif}
\setsansfont[Mapping=tex-text]{Libertinus Sans}
\setmonofont{Libertinus Mono}

\pagestyle{empty}

\usepackage{polyglossia}

\def\testop{\int}
%\def\testop{\iint}
%\def\testop{\iiint}
%\def\testop{\iiiint}
%\def\testop{\oint}
%\def\testop{\oiint}
%\def\testop{\oiiint}
%\def\testop{\intclockwise}
%\def\testop{\varointclockwise}
%\def\testop{\ointctrclockwise}

\def\mathtest{
\[
{\textstyle \testop_{W}^b f(x) = \testop\limits_{W}^b f(x)} =\testop\limits_{W}^{b}f(x)dx= \testop_{W}^{b}f(x)dx = f(b)-f(W)
\]
}

\begin{document}
Latin Modern:

\mathtest

Libertinus Math:

{\setmathfont{LibertinusMath-Regular.otf}
\mathtest
}

Libertinus Math (+ss08): 

{\setmathfont{LibertinusMath-Regular.otf}[RawFeature={+ss08}]
\mathtest
}

STIX Two (default):

{\setmathfont{STIX2Math.otf}
\mathtest
}

STIX Two (+ss08):

{\setmathfont{STIX2Math.otf}[RawFeature={+ss08}]
\mathtest
}
\end{document}
```
