### ISSUE TITLE
Enable & release WOFF2 builds

### ISSUE THREAD

**Issue by alerque** [alerque/libertinus#363]
To date I haven't enabled webfont builds on purpose because I wanted to make sure the OTF releases built with `fontmake` were 100% up to par with the original build system first. Now that that's behind us, I think it's worth looking into how the WOFF2 builds look & function. See also #362 for the fact that people are using the poorly compressed OTFs online and want it on a CDN. Whether we do or don't get a CDN going WOFF2 compression would be a good thing for these guys.

**Comment by lutetiensis** [comment]
I know nothing about WOFF2, but I can definitely test your builds!
