### ISSUE TITLE
Link Uni A789, Modifier letter colon to Uni 003A, Colon

### ISSUE THREAD

**Issue by kopeckyf** [alerque/libertinus#364]
There's a Unicode slot for ꞉ (Unicode A789), which is exactly the same glyph as the regular colon. It's purpose is purely technical, particularly in linguistic texts. It is thus sufficient for A789 to resemble 003A, the usual colon.

I'd be happy to create a PR for this fix, but I'm unsure how to link to Unicode characters in FontForge (or any other software), so that future changes to 003A would take effect on A789 as well.

**Comment by alerque** [comment]
I'm pretty sure one way is to make a new glyph and copy the shape from the old one and paste by reference. The shape but not other properties should be linked. However I'm not sure that's the best way, it might make more sense to copy the glyph as part of the build process. I'll have to look into which approach is better for this.

By the way do you have any docs you can point me towards for how this codepoint is actually used? Are there any special spacing considerations that differ from the regular colon (i.e. should it by assigned to the same kerning category)?

**Comment by kopeckyf** [comment]
In the SIL Doulos and Charis fonts, kerning the modifier letter colon is exactly the same as the regular colon. However, they have reduced the vertical skip between the upper and lower dot, and both dots seem to have a slightly reduced diameter. I don't know if it is necessary to follow SIL here. Even in the SIL fonts, the two colons can be distinguished only when they are printed right next to each other, or when there's a large zoom on the output.

The reasoning behind introducing the modified letter is reported in this PDF, in the section Case study #3: https://www.sil.org/sites/default/files/best_practice_for_non-alphabetic_characters_v2_0.pdf

**Comment by khaledhosny** [comment]
You can either use references, or map the same glyph from different code points (IIRC, space and nbspace do this, as an example).

**Comment by moyogo** [comment]
U+A789 is supposed to visibly smaller that colon. The proposal ([L2/05-097](https://www.unicode.org/L2/L2005/05097-latin-orth.pdf)) to add it to Unicode has the following note:
> Compared with a typical colon glyph, the dots of the MODIFIER LETTER COLON should be closer together, and the side bearings should be narrower. (Note that the sample in Figure 15 is not as good an examplar in this regard as the other samples.) 

Charis SIL, Doulos SIL but also Noto Sans, Noto Serif and Times New Roman do distinguish the two this way.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1923747/95000136-281b5a00-05b6-11eb-8b70-e4abc3cb9ba2.png">

I would not recommend using the same glyph for both U+003A and U+A789, nor using a composite glyph of the first for the second.

**Comment by alerque** [comment]
I was just this minute half way through adding these as composites! Thanks for the heads up.

**Comment by alerque** [comment]
So here's the rundown of fonts I happen to have installed that support this (not including weight and other variants):

![image](https://user-images.githubusercontent.com/173595/95002525-c2db5f00-05dd-11eb-9bd6-1550cdb2784b.png)

<details>
<summary>SILE sources</summary>

```sile
\begin{document}
\neverindent
\nofolios
\language[main=und]
\font[size=40pt]
\begin{script}
SILE.registerCommand("sample", function(options, content)
SU.dump(content[1])
	SILE.call("font", { style = "Book", family = content[1] }, {":꞉ "..content[1]} )
	SILE.call("hfill")
	SILE.call("break")
end)
\end{script}
\sample{Libertinus Serif}
\sample{Libertinus Sans}
\sample{Charis SIL}
\sample{Doulos SIL}
\sample{Gentium Plus}
\sample{Free Serif}
\sample{Free Sans}
\sample{Liberation Serif}
\sample{Liberation Sans}
\sample{Noto Serif}
\sample{Noto Sans}
\sample{Deja Vu Sans}
\sample{Deja Vu Serif}
\sample{Roboto}
\sample{Pecita}
\end{document}
```

</details>

Pecita is a bit of a surprise here, but hey. Roboto seems to be the only one that also makes the dots smaller as well as bringing them together.
