### ISSUE TITLE
Double bar [U+2016] in Mono is sloped

### ISSUE THREAD

**Issue by alerque** [alerque/libertinus#369]
For some reason the double bar glyph at U+2016 in Libertinus Mono is sloped, as if this was an Italic style. I have no idea why that would be or if there is a reason behind it, but at first blush this strikes me as wrong. Investigate and possibly correct...

**Comment by richirisu** [comment]
The same seems to apply to 'Double Low Line' U+2017 as well, although it is hard to see if not enlarged.

**Comment by alerque** [comment]
Thanks for reporting that @richirisu.

Given that there has never been an Italic version of the Mono font to accidentally copy these from I have no idea where this design came from. I looked through a pile of other fonts and some Unicode documents and can't see any reason at all these should be slanted.
