### ISSUE TITLE
Libertinus Keyboard glyph corresponding to [U+0140] is erroneous

### ISSUE THREAD

**Issue by orestesmas** [alerque/libertinus#372]
This glyph corresponds to Unicode U+0140 code point "Latin Small Letter L with middle dot". The problem is that the dot should appear at the *right* side of lowercase "L", and in that font it is located to the left (before the "L")

In a Linux computer with X-Window system the «middle dot L» can be reached with Ctrl+Shift+U followed by the sequence "0140"+ENTER.

The companion glyph corresponding with the Capital "L" is correct.

**Screenshots / logs**

Here is a screen capture showing the problem with « ŀ » (in yellow), comparing this glyph in capital and lowercase form for 2 different typefaces: Libertinus Serif and Libertinus Keyboard.

![image](https://user-images.githubusercontent.com/411690/95616573-48da2880-0a6a-11eb-8682-893ddbbbbb65.png)

**Comment by alerque** [comment]
Thanks for the report. The seems to be a hold over all the way back to Linux Biolinum Keyboard. I don't know how the dot came to be on that side, but given every other face in the family has it on the right it seems non-sensical to me.
