### ISSUE TITLE
How do I access the salt alternative style set?

### ISSUE THREAD

**Issue by iacchi** [alerque/libertinus#379]
@alerque has replied to a very old bug of mine in the Libertine font bug tracking system [here](https://sourceforge.net/p/linuxlibertine/bugs/326/), and suggested that Libertinus' stylistic alternate set (+salt) has a solution to my issue. Now, forgive my ignorance but" how do I access this alternate set (e.g. in LibreOffice)? I've tried to google a bit, but I haven't found an answer.

**Comment by alerque** [comment]
In LibreOffice Writer, toggling Open Type features are available in:

Format → Character → Font → Features.

For your capital J issues, the full name of the `+salt` feature flag is "Stylistic Alternatives".

**Comment by alerque** [comment]
Screenshot from current LO Writer:

![image](https://user-images.githubusercontent.com/173595/95783360-54338b00-0cda-11eb-9956-9c5850d98fef.png)

It looks like you can probably skip the dialog box and just set your font as `Libertinus Serif:salt`.

**Comment by iacchi** [comment]
Nice, thank you very much! What about Latex? (sorry...)

**Comment by hvoss49** [comment]
```
\documentclass[12pt]{article}
\usepackage{libertinus-otf}
\begin{document}

JKR \LSS02 JKR

\end{document}
```
![Bildschirmfoto 2020-10-12 um 21 36 40](https://user-images.githubusercontent.com/12891199/95783914-1bdc7e80-0cd3-11eb-809b-2a66a84f6f8e.png)

**Comment by alerque** [comment]
I was just trying to scrounge that up @hvoss49. Unfortunately I just tried and that doesn't work for me. No idea what happened. I get the name J glyph both places with for MWE copied line for line.

Also the issue the OP has is with the Italic style and he wants the opposite direction (plainer glyph design, not the fancier one that is the default). So this probably needs flip-flopping. But still I'm confused why I don't get the same result you show!

**Comment by hvoss49** [comment]
I used lualatex and will try it with xelatex tomorrow. Just did a shutdown on  my system.

**Comment by alerque** [comment]
In `lualatex` your user of `\LSS02` works for me too. It does nothing in `xelatex`.

In `xelatex` substituting your `\LSSO2` with `\addfontfeatures{Style=Alternate}` does the trick for me. Is there a bug tracker for the `libertinus-otf` CTAN package?

**Comment by iacchi** [comment]
In the meantime, thank you very much for all your help (and for finally having a solution to this madness!)

**Comment by hvoss49** [comment]
@alerque : It is fixed now with the next upload. There was a missing  leading + sign for `RawFeature=+ss20`.

**Comment by alerque** [comment]
Thanks @hvoss49 for the fix and the LaTeX usage tips. For future reference is there an issue tracker for that package or should I just ping you here if something comes up with it?

Unless @iacchi has objections I think we can call this issue a wrap!

**Comment by hvoss49** [comment]
> Am 13.10.2020 um 09:03 schrieb Caleb Maclennan <notifications@github.com>:
> 
> 
> Thanks @hvoss49 <https://github.com/hvoss49> for the fix and the LaTeX usage tips. For future reference is there an issue tracker for that package or should I just ping you here if something comes up with it?
> 
> 


Pinging is enough, I read all messages here

**Comment by iacchi** [comment]
Yes, I think we can wrap it up.
