### ISSUE TITLE
Conflict LibreOffice vs. Libertinus 7.010

### ISSUE THREAD

**Issue by kimmus** [alerque/libertinus#385]
The new version of Libertinus conflicts with LibreOffice Writer 7.0.2.2. Font is set to Libertinus Serif:onum&pnum&dlig, i.e. I am using oldstyle proportional numbers and discretionary ligatures. Both display abnormally: see attached screen capture.
![LibertinusBug](https://user-images.githubusercontent.com/60458875/95819863-a7f1b300-0d72-11eb-9206-9a6d3efd5c66.PNG)

**Comment by kimmus** [comment]
Since I can’t find a way to edit the above, I’ll add a comment. The first two lines of the screen capture should read: ‘Crawford wrote the _Three Chants for Women’s Chorus_ in 1930 while studying in Germany on a Guggenheim scholarship. They were…

**Comment by alerque** [comment]
(You can edit comments with the pencil button above and to the right of each post).

I just fired up LibreOffice (I have 7.0.2.2 as well) and copied your two lines of text into Writer. My system installed Libertinus Serif is v7.010. I then set the font to `Libertinus Serif:onum&pnum&dlig` as in your comment, and it rendered with all those open type features just fine:

![image](https://user-images.githubusercontent.com/173595/95823873-0ef17680-0d37-11eb-9584-d63094ff1c1b.png)

**Comment by kimmus** [comment]
Thanks — this may have been the problem. In any case, I explicitly deleted/uninstalled every occurrence of the Libertinus fonts, rebooted, and reinstalled, and the above-mentioned problem is gone. There does however seem to be a problem with Libertinus Serif SemiboldItalic in LibreOffice, but I will make a separate report on that.
