### ISSUE TITLE
Review dropping artificialy family split for legacy app support

### ISSUE THREAD

**Issue by alerque** [alerque/libertinus#392]
Per discussion starting [here](https://github.com/alerque/libertinus/issues/390#issuecomment-708299697) it has come up that Libertinus has sacrificed some convenience in modern applications (e.g. LibreOffice Writer) like having all the styles listed in the character formatting dialogue box in order to support legacy apps that can't understand more that four styles per family.

> The difference you note from Linux Libertine is the result of the workaround added in 82bbc652 and made its way into Libertinus [releases at v6.7](https://github.com/alerque/libertinus/releases/tag/v6.7). This is an unfortunate situation where we can either do the right thing by modern apps *OR* allow the Semibold variants to be used legacy applications that only understand a maximum of 4 fonts per family, but not both.
>
> I would be interested in reviewing whether it is still worth keeping that workaround in place –and possibly more wiling that Khaled to leave legacy application support behind– but I'm going to put off that research, discussion, and decision for another time. One possible solution would be to add a 'legacy' release package variant aimed at such people while encouraging normal usage using the modern featured variants. For the moment the current release is badly broken and I'm going to release it with the same legacy app workaround untouched to at least get parity with older working releases.

**Comment by khaledhosny** [comment]
There should be no sacrifice here, but LibreOffice is very broken when it comes to families with more than R/B/I/BI styles, so I wouldn’t draw any conclusions from LibreOffice behaviour alone. The naming scheme I used (bugs aside) is spec-conformant and supported by a wide range of applications.

**Comment by alerque** [comment]
You appear to be right as usual. All the machinery is there for apps to do better. LibreOffice is in some limbo land where it supports more than the original spec and isn't technically a legacy app with only 4x fonts per family, but at the same time it doe not properly support the official use of new nameids to link more fonts into a family in a backward compatible way.

There are a *ton* of open issues tracking a hosted of related quirks in LibreOffice, but here is the [most relevant bug report I found](https://bugs.documentfoundation.org/show_bug.cgi?id=35538) for those interested in tracking this. There are also platform specific variants and a host of more specific issues that all boil down to about the same thing.
