### ISSUE TITLE
Support for Macedonian italics

### ISSUE THREAD

**Issue by d125q** [alerque/libertinus#394]
Currently, the font includes support for Serbian italics, which is enabled by the SRB language tag.  Serbian italics differ from, e.g., Russian, when it comes to the letters б, г, д, п, and т.  However, there is no similar support for Macedonian italics.

Here is the current difference between Serbian and Russian:

![Serbian vs. Russian italics](https://user-images.githubusercontent.com/7765538/96178870-5131d800-0f30-11eb-8015-f7195d0ca4b2.png)

And here is a reference on what the Macedonian italics should look like:

![Macedonian italics](https://user-images.githubusercontent.com/7765538/96104343-03d64c00-0ed9-11eb-8e78-d3b4058cd1e5.png)

As you can see, they should be identical to the Serbian ones except there should also be a special version of the letter ѓ.  (This letter does not exist in the Serbian alphabet.)

**Comment by alerque** [comment]
I'd be happy to see this supported. Is this something you'd be able to contribute?

**Comment by d125q** [comment]
Yes, I’ll look into it ASAP.  I guess we can move things over to #29?  Thanks a lot!

**Comment by Crissov** [comment]
Source for the picture is [Wikicommons](https://commons.wikimedia.org/wiki/File:Cyrillic_cursive.svg), by the way. There are similar ones which may be more informative.

**Comment by alerque** [comment]
@aleslavista and @Crissov in case you are interested this is fixed in the master branch now. Until the next tagged release you can always download and run [development builds attached as artifacts to each commit](https://github.com/alerque/libertinus/actions?query=workflow%3AFontship+branch%3Amaster).
