### ISSUE TITLE
Proposal to make Th ligature not rare

### ISSUE THREAD

**Issue by thomasjwood** [alerque/libertinus#395]
Love this package, brilliant resource, tons of improvements over the last Libertine release.

One (modest) suggestion--would it be possible to move the Th ligature back from the "Rare" subset? This would be made consistent with the original Libertine.

**Comment by alerque** [comment]
Thanks and I'm glad you like the fonts, I hope you continue to enjoy them.

No I don't think the Th ligature is coming back to the default set. Personally I'm not that opposed to it but there sure are plenty of people that are! I think where it is now in `dlig` (discretionary ligatures, discretionary is not quite the same thing as "rare") is a good home for it.

See #104 for discussion for where this was removed from the default set. I initially argued there should be a stylistic set to disable it not the other way around, but moving the cheese *again* just to toggle whose preferences are the current most 'squeaky wheel' would not be a good thing.
