### ISSUE TITLE
Missing double arrows

### ISSUE THREAD

**Issue by redtrumpet** [alerque/libertinus#403]
Some double arrows like `U+21C4` ⇄ are missing in the Libertinus Math font. For a more complete list, see the following screenshot:

 ![screenshot of missing arrows in fontforge](https://imgur.com/vkFsAXz.png)

This is in particular relevant for LaTex users, as `\leftrightarrow` does not work because of this.

**Comment by alerque** [comment]
Probably not just a *Libertinus Math* problem, I'm guessing there are some holes that could be filled in other faces as well.

**Comment by ivo-s** [comment]
Hey, I presume no one is working on this; I'll fill in the arrows in some spare time, might take a bit. I can't make any promises about the wavy arrows, because I want them to be pointing straight left/right and also have a nice wavy shape, which I can't seem to get right. Probably I'll skip them.

**Comment by alerque** [comment]
@redtrumpet Now that @ivo-s has kindly contributed the work to add these glyphs you can find them in the latest development builds. Under the "Actions" tab of the repository look for the "Fontship" action, find the latest commit, and then download the artifact files that are attached to it. They will of course be in the next release.
