### ISSUE TITLE
Latex font from ctan doesn't work with pdflatex compiler, plus conflict with amsfonts

### ISSUE THREAD

**Issue by iacchi** [alerque/libertinus#404]
As the title says. I have a document I'm writing (I'm using Overleaf to write it), and I'd like to use libertinus as font. After loading the package, document compilation fails when using the pdflatex compiler. It compiles when using xelatex and lualatex, but it's still throwing some errors (in the amsfonts package) that are not there if I'm using the libertine font instead, so maybe there are some incompatibility between the libertinus and amsfonts packages?

**Comment by alerque** [comment]
Thanks for the report @iacchi. I'm all for getting this sorted out, but I need a closer look at what is actually wrong. I know *about* Overleaf but haven't used it much. Is there any way you could throw together a MWE and share it here such that we can replicate the problem either on Overleaf or locally?

**Comment by iacchi** [comment]
Overleaf is just a standard full ctan latex installation kept updated, with an integrated text editor to write your document - nothing that you can't replicate on your local machine really without Overleaf. Anyway, if you tell me what a MWE is, I'll be happy to oblige :P I guess the E stands for example and the w maybe for working?

**Comment by alerque** [comment]
MWE: Minimum Working Example. Basically the smallest self-contained document that actually exibits a given problem with as little interference from potential other culprits as possible. In other words not the source for your book project with a whole bunch of moving parts, just a stripped down single document and specific command to run the replicate the problem.

**Comment by iacchi** [comment]
Maybe it's not the bare minimum, but it's small enough: https://pastebin.com/axpurpnD
The incompatibility with amssymb might be because libertinus is providing math characters as well (libertine is not) and so the amssymb package is not required at all, but I haven't tried yet if my documents displays properly without it. The problem with the pdflatex compiler remains though.

(on a side funny note, I just realised: I opened the issue not found :P)

**Comment by sieversMartin** [comment]
It works just fine with pdflatex, when you use the `libertinus` "meta package" instead of `libertinus-otf`, which is only meant for Unicode negines like XeTeX and LuaTeX. `libertinus` loads `libertinus-type1` when used with pdflatex, otherwise `libertinus-otf` is loaded.

**Comment by sieversMartin** [comment]
BTW: The error messages give a good hint at the problem:
```
! Package unicode-math Error: Cannot be run with pdftex!
(unicode-math)                Use XeLaTeX or LuaLaTeX instead.
```

**Comment by iacchi** [comment]
That makes sense I guess. In a previous support ticket I was told to use the package libertinus-otf, so I didn't even know the meta package existed. I'm also quite new to latex in general, so not all error messages necessarily make sense to me :P Thanks for the tip @sieversMartin !
