### ISSUE TITLE
Stylistic Set 08

### ISSUE THREAD

**Issue by hvoss49** [alerque/libertinus#424]
Is there a a short documentation (example) which shows the use of fontfeature +ss08 for math?

**Comment by RGB-es** [comment]
> Is there a a short documentation (example) which shows the use of fontfeature +ss08 for math?

In the document preamble 

`\setmathfont{Libertinus Math}[RawFeature={+ss08}] ` 

It works on XeTeX, but I think it's the same for LuaTeX

**Comment by hvoss49** [comment]
I see! I used lualatex where it doesn't worked for me:

```latex
\listfiles
\documentclass{article}
\usepackage{libertinus-otf}
\begin{document}

$\int_1 ^\infty \frac1{x^2}\symup d x = 1$ 
\[ \int_1 ^\infty \frac1 {x^2}\symup d x = 1 \]
\[ \int \limits_1 ^\infty \frac1 {x^2}\symup d x = 1 \]

\setmathfont[RawFeature={+ss08}]{LibertinusMath-Regular.otf}

$\int_1 ^\infty \frac1{x^2}\symup d x = 1$ 
\[ \int_1 ^\infty \frac1 {x^2}\symup d x = 1 \]
\[ \int \limits_1 ^\infty \frac1 {x^2}\symup d x = 1 \]

\end{document}
```

**Comment by RGB-es** [comment]
Try not using the libertinus-otf package, but manually call all the fonts

`
\documentclass[english]{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}
\setmonofont{Libertinus Mono}
\setmathfont{Libertinus Math}[RawFeature={+ss08}] 
`
You can use that to also pass OpenType options to the main font with `\setmainfont{font-name}[RawFeature={+xxxx}]`

**Comment by hvoss49** [comment]
I always use the package, because I am the author ... :-)

**Comment by alerque** [comment]
There are some more examples of usage in TeX in code snippets on [the issue where this feature was requested](https://github.com/alerque/libertinus/issues/357).

**Comment by hvoss49** [comment]
Yes, that one I was looking for but didn't found it ... 
thanks

**Comment by Explorer-cc** [comment]
> Is there a a short documentation (example) which shows the use of fontfeature +ss08 for math?

@RGB-es So is there any where documented that we can use `+ss08` RawFeature for slanted `\int`? I didn't found any documentation intrduction at [here](https://mirrors.ctan.org/fonts/libertinus-fonts.zip).🤔🤔
