### ISSUE TITLE
glyph request: small caps h with combining breve below

### ISSUE THREAD

**Issue by vjeffcott** [alerque/libertinus#432]
I'm putting together reading notes on Hittite. Convention in the literature dictates that embedded Sumerian and Akkadian words be transliterated in roman capitals and slanted capitals respectively. Both languages have a sound transliterated ḫ.

It would be very nice to have this work in Libertinus; for now I'm using the combining minus sign.

**Comment by kimmus** [comment]
Could you use U+029C with U+032E: ʜ̮. At present the Combining Breve Below doesn’t centre accurately below the ʜ, but this could perhaps be fixed?

**Comment by alerque** [comment]
> roman capitals and slanted capitals

Capitals or small-caps?

**Comment by vjeffcott** [comment]
> Could you use U+029C with U+032E: ʜ̮. At present the Combining Breve Below doesn’t centre accurately below the ʜ, but this could perhaps be fixed?

OK, with a bit of experimentation I've figured out how to get LaTeX not to pre-compose the character _before_ applying small-caps. Thank you!

> > roman capitals and slanted capitals
> 
> Capitals or small-caps?

Usually small-caps. Regular caps show up sometimes in published works but frankly I just think that looks bad.

**Comment by khaledhosny** [comment]
The simplest way is to fix it similar to #303, and if the anchors are not good they should be fixed too. The more involved way is to add pre-composed glyphs, but this will require adjusting kerning and any features that might be interacting with the smallcaps.

**Comment by alerque** [comment]
The fix for this is merged now and will be in the next release, whenever that is. Until then you can get this fix and everything else that has been merged by using the artifacts attached to the [latest builds on the master branch](https://github.com/alerque/libertinus/actions/workflows/fontship.yml?query=branch%3Amaster+event%3Apush).
