### ISSUE TITLE
Math font with exponent can not be displayed correctly in MS PowerPoint

### ISSUE THREAD

**Issue by TingjieGuo** [alerque/libertinus#465]
**Describe the bug**
Math font with exponent can not be displayed correctly in MS PowerPoint

**Steps to reproduce**
Insert an equation in PowerPoint and write any expressions containing exponent

**Expected vs. actual behavior**
Exponent is not displayed as what I type.

**Screenshots / logs**
If I write the following equations
![image](https://user-images.githubusercontent.com/8663013/111601131-5e4e3e00-87d2-11eb-9c64-0ed59b218a76.png)

I got the following results in PowerPoint
![image](https://user-images.githubusercontent.com/8663013/111601264-79b94900-87d2-11eb-8705-b0b3e25cfab8.png)

**Comment by TingjieGuo** [comment]
This seems a bug of PowerPoint but I'm not sure...

**Comment by DJakov-beep** [comment]
Hi, I tested a few things and it seems that PowerPoint has - in contrast to MS Word - serious Problems with Opentype Math Fonts other than its default Cambria Math. Mysteriously it can handle some fonts, while it bugs at others with a seemingly random behaviour, as you can see here (results are equal, no matter if equations were created in MS Word and then copy- pasted into PowerPoint or typed directly in PowerPoint )
![image](https://user-images.githubusercontent.com/69644007/111631265-7d10fc80-87f3-11eb-8e73-2d54cb4cbeae.png)

Strangely it displays the exponents correctly, when one formats them in **bold**, here for Libertinus Math:
![image](https://user-images.githubusercontent.com/69644007/111631955-48ea0b80-87f4-11eb-8c1f-b1d3201ca969.png)

Alternatively you can create the equation in Word, take a screenshot and insert it into PowerPoint. During a presentation a viewer cannot distinguish if the equations are "real" or only bitmap.

**Comment by TingjieGuo** [comment]
Yeah I realized that too, indeed the issue with powerpoint. Thanks for the thorough test!

**Comment by KrasnayaPloshchad** [comment]
This should be feedback to Microsoft.

**Comment by DJakov-beep** [comment]
@KrasnayaPloshchad  Done. I contacted the development team of Office Math and they responded. They possibly will have a look at it. But forecasts when the Issue will be solved are not possible.
