### ISSUE TITLE
Smallcaps stopped working beginning with 6.12 in Illustrator for serif/sans

### ISSUE THREAD

**Issue by Tyrhung** [alerque/libertinus#482]
Hi there!

I just noticed (after creating a figure with a Libertinus font after a while) that the small caps feature stopped working in Adobe Illustrator (25.2.1, if that matters) when using the Libertinus Serif or Libertinus Sans fonts **beginning with 6.12**:
![LibertinusSansSC](https://user-images.githubusercontent.com/88267193/127763621-0851d6f2-20db-4c5e-a911-c2d4758bd708.PNG)
![LibertinusSerifSC](https://user-images.githubusercontent.com/88267193/127763622-4e59a59b-8e7e-4823-b36f-ef4a921a2aa6.PNG)
(as you can see, only the i gets capitalized)

In versions prior to 6.12, small caps work as expected. Strange enough, even with >=6.12 small caps still work for Libertinus Serif Display and Libertinus Math (the latter seems to be a current workaround for Libertinus Serif):
![LibertinusSerifDisplaySC](https://user-images.githubusercontent.com/88267193/127763705-b70d832b-fde7-43e1-bcf4-fa89c8dbb2ef.PNG)
![LibertinusMathSC](https://user-images.githubusercontent.com/88267193/127763706-f8db87b9-9129-49d9-8e6e-eb58204ee18b.PNG)

From the changelog of 6.12 I would expect that

> Building the fonts no longer use FontForge.

may be the issue here? I am not familiar with the font creation process but if you want me to try something out, I can do that :-)

PS: I really love this font!

**Comment by RGB-es** [comment]
No problem with Small Caps (+smcp) on Libertinus 7.040 when using XeTeX or LibreOffice. Maybe an Illustrator problem?

**Comment by Crissov** [comment]
Since small capital _i_ soll seems to work, I’d assume some but with the handling of the Turkish _i_.

**Comment by khaledhosny** [comment]
Duplicate of #434. Try using the so called [World Ready Composer](https://helpx.adobe.com/creative-suite/kb/arabic-hebrew.html), it might work.

**Comment by khaledhosny** [comment]
I have read that Adobe’s default Composer does not support one to many substitutions, and Libertinus small caps features have some.

**Comment by Tyrhung** [comment]
Thanks for your help. Unfortunately, my Illustrator version does not have a World Ready Composer, so I cannot try whether this helps. However, as far as I understand, this is an Illustrator issue and not an issue of the font. The bug is reported to Adobe: https://illustrator.uservoice.com/forums/601447-illustrator-desktop-bugs/suggestions/44028336-small-caps-do-not-work-for-libertinus-font-open-t
