### ISSUE TITLE
math: uneven spacing of ⟨f,f⟩ and ‖f‖

### ISSUE THREAD

**Issue by mdeff** [alerque/libertinus#495]
**Describe the bug**
When typesetting ⟨f,f⟩ and ‖f‖, the spacing between the letter f and the angles and bars is uneven.

**Steps to reproduce**
Compile the following document with `latexmk -pdflua`.
```tex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{LibertinusMath-Regular.otf}
\newcommand*{\norm}[1]{{\ensuremath{\left\|{#1}\right\|}}}
\newcommand*{\inner}[1]{{\ensuremath{\left\langle{#1}\right\rangle}}}
\begin{document}
    \[
        \inner{f, f}       \hspace{2em}
        \norm{f}_2^2       \hspace{2em}
        \inner{g, g}       \hspace{2em}
        \norm{g}_2^2       \hspace{2em}
    \]
\end{document}
```

**Expected vs. actual behavior**
The spacing should be similar on the left and right, as it is when typesetting ⟨g,g⟩ and ‖g‖.

**Screenshots**
![20211227_191848](https://user-images.githubusercontent.com/6806065/147497860-823b0168-9138-443e-90b5-266168b062e8.png)

**Comment by mdeff** [comment]
Note that many OpenType math fonts have this issue.

For example, compare the Latin Modern OpenType (`\setmathfont{latinmodern-math.otf}`)
![20211227_155345_latinmodern](https://user-images.githubusercontent.com/6806065/147498643-e2aeb8d0-905b-49e0-a6a7-47d567c2f55b.png)

with the Latin Modern from TeX (i.e., without `\usepackage{unicode-math}`):
![20211227_155248_without_unicode-math](https://user-images.githubusercontent.com/6806065/147498645-c028b86e-3f7c-42ff-868a-81add60c7374.png)

**Comment by khaledhosny** [comment]
Are you using LuaTeX? This is a known LuaTeX issue as it ignores italic correction by default. If you search tex.stackexchange.com/ you might find a way to activate the italic correction. XeTeX should not have this problem.

**Comment by mdeff** [comment]
Thanks for the hint! I'm using LuaTex.

There's indeed an answer on the [TeX Stack Exchange](https://tex.stackexchange.com/a/31440) where you suggest the following:
```tex
\everymath{\luatexcatcodetable\CatcodeTableLaTeX}
\everydisplay{\luatexcatcodetable\CatcodeTableLaTeX}
```
But `\luatexcatcodetable` and `\CatcodeTableLaTeX` are giving me an "undefined control sequence" error. Would you know of any other way?

XeTeX (i.e., compiling with `latexmk -pdfxe`) indeed does not have this problem.

**Comment by mdeff** [comment]
STIX Two and Cambria don't have this problem, neither with LuaTeX nor XeTeX.

**Comment by redtrumpet** [comment]
The pics produced by the `lua-visual-debug` package indicate, that italic correction does indeed not work for "STIX Two" either. Here is what it looks like without `unicode-math`:

[![without unicode-math][2]]

Note the yellow box to the right of the second *f*, which indicates kerning. Now with `\usepackage{unicode-math}`, it looks like this:
[![with unicode-math][1]]

Using `\setmathfont{STIX Two Math}` produces

[![stix two][4]

which has still no kerning. However, the box of the *f* seems to be bigger, preventing a real issue. But if you compare the STIX Two Math font to Libertinus Math in fontforge you will see that both have an "italic correction" indicator, which is not respected.


  [1]: https://i.stack.imgur.com/vUM53.png
  [2]: https://i.stack.imgur.com/dq1yW.png
  [3]: https://i.stack.imgur.com/8zopX.png
  [4]: https://imgur.com/EaNVOmD.png
  [5]: https://imgur.com/2zioW5J.png
  [6]: https://imgur.com/Czicg7O.png

**Comment by redtrumpet** [comment]
There seems  to be a solution by adding `\mathitalicsmode=1` in the preamble. However, for some reason I don't understand yet, you have to remove the surrounding brackets `{` and `}` from the commands. So

```
\mathitalicsmode=1
\newcommand*{\norm}[1]{{\ensuremath{\left\|#1\right\|}}}
\newcommand*{\inner}[1]{{\ensuremath{\left\langle#1\right\rangle}}}
```
seems to work.

**Comment by mdeff** [comment]
That works! Thanks for investigating and sharing your findings.

**Comment by mdeff** [comment]
Though italic correction is not ideal for every font. For example, with STIX Two, italic correction introduces too much space. (Although that's a slight problem compared to the overlap with Libertinus.)

It's too bad that different fonts encode this information differently. 😕

`\setmathfont{STIX Two Math}` without `\mathitalicsmode=1`:
![20220427_004444](https://user-images.githubusercontent.com/6806065/165404916-6e6087ba-895e-41c2-b25b-7f25d16d9b24.png)

`\setmathfont{STIX Two Math}` with `\mathitalicsmode=1`:
![20220427_004229](https://user-images.githubusercontent.com/6806065/165404691-d417029b-9573-4830-bf92-627e12ea66aa.png)

**Comment by khaledhosny** [comment]
STIX fonts are under active development, please report issues you have https://github.com/stipub/stixfonts/issues (they might be working around the broken LuaTeX default by increasing the right sidebearing and forgot to remove the italic correction).

**Comment by Firestar-Reimu** [comment]
need package `physics`
```
\ket{f} |f\rangle \expval{f,f} \langle f,f \rangle
```

### without `\mathitalicsmode=1`
```
\usepackage{unicode-math}
\unimathsetup{mathrm=sym,mathbf=sym,mathsf=sym,bold-style=ISO}
\usepackage[math=+ss08]{libertinus-otf}
```

![Screenshot_20221115_192800](https://user-images.githubusercontent.com/65082432/201908571-3446dfc1-f44e-4c3f-8bb2-0f7685967ec3.png)

### with `\mathitalicsmode=1`

```
\mathitalicsmode=1
\usepackage{unicode-math}
\unimathsetup{mathrm=sym,mathbf=sym,mathsf=sym,bold-style=ISO}
\usepackage[math=+ss08]{libertinus-otf}
```
![Screenshot_20221115_192901](https://user-images.githubusercontent.com/65082432/201908774-7e6fdafd-8bcc-4137-9c82-af0cb0eb1cd2.png)

**Comment by Firestar-Reimu** [comment]
\mathitalicsmode=1 has limited effect, for example: $ \left\langle f,f\right\rangle $ has correct spacing, but $ \left\langle {f,f}\right\rangle $ still outputs wrong spacing .

The definition of \expval in physics looks like this:
```
\DeclareDocumentCommand\expectationvalue{ s s m g }
{ % Expectation value
\IfNoValueTF{#4}
{
\IfBooleanTF{#1}
{\vphantom{#3}\left\langle\smash{#3}\right\rangle} % Starred implicit form: no resizing
{\left\langle{#3}\right\rangle} % Normal implicit form: auto sizing
}
{
\IfBooleanTF{#1}
{
\IfBooleanTF{#2}
{\left\langle{#4}\middle\vert{#3}\middle\vert{#4}\right\rangle} % Double starred explicit form: total auto sizing
{\vphantom{#3#4}\left\langle\smash{#4}\middle\vert\smash{#3}\middle\vert\smash{#4}\right\rangle} % Starred explicit form: no resizing
}
{\vphantom{#3}\left\langle{#4}\middle\vert\smash{#3}\middle\vert{#4}\right\rangle} % Normal explicit form: only resize based on bra/ket arguments
}
}
```
You can see it added { } or \smash. Both currently invalidate the automatically added italic correction. It should be because, regardless of { } or \smash, their contents will form a new ord atom, and no italic correction is applied to the end of this ord atom.

Italic correction can only be added manually: \expval{f,f\/}.

**Comment by Firestar-Reimu** [comment]
> **`\mathitalicsmode=1` has limited effect**

so maybe increase width of letter `f` is the ultimate solution?

**Comment by Firestar-Reimu** [comment]
```
\documentclass{article}
\usepackage{unicode-math}
\mathitalicsmode=1
\setmathfont{LibertinusMath-Regular.otf}
\newcommand*{\norm}[1]{{\ensuremath{\|{#1}\|}}}
\newcommand*{\inner}[1]{{\ensuremath{\langle{#1}\rangle}}}
\begin{document}
    \[
        \inner{f, f}       \hspace{2em}
        \norm{f}_2^2       \hspace{2em}
        \inner{g, g}       \hspace{2em}
        \norm{g}_2^2       \hspace{2em}
    \]
\end{document}
```

![Screenshot_20230316_203758](https://user-images.githubusercontent.com/65082432/225619311-ec702e6a-9e13-440f-9917-1539c7b6fbc1.png)

```
\documentclass{article}
\usepackage{unicode-math}
\mathitalicsmode=2
\setmathfont{LibertinusMath-Regular.otf}
\newcommand*{\norm}[1]{{\ensuremath{\|{#1}\|}}}
\newcommand*{\inner}[1]{{\ensuremath{\langle{#1}\rangle}}}
\begin{document}
    \[
        \inner{f, f}       \hspace{2em}
        \norm{f}_2^2       \hspace{2em}
        \inner{g, g}       \hspace{2em}
        \norm{g}_2^2       \hspace{2em}
    \]
\end{document}
```
![Screenshot_20230316_203855](https://user-images.githubusercontent.com/65082432/225619553-b41c8a13-cbae-4345-a2f4-3e78748ef21b.png)
