### ISSUE TITLE
Monospace glyphs are wider when bold

### ISSUE THREAD

**Issue by RiedleroD** [alerque/libertinus#497]
**Describe the bug**
The bold monospace glyphs are wider than the regular monospace glyphs.

**Steps to reproduce**
Open some text in e.g. Kate & set the styling to Libertinus Mono - then look for something that's styled as bold & see that it's a wider glyph than regular ones.

**Expected vs. actual behavior**
All glyphs should be the same size; it's supposed to be monospaced.

**Screenshots / logs**
![image](https://user-images.githubusercontent.com/57227431/154058529-a2e74459-33b5-41d4-817e-292efbe2a184.png)

**Comment by kimmus** [comment]
Libertinus Mono only exists as regular, there is no bold style. So any ‘bold’ form created by e.g. word-processing software is outside the control of the font.

**Comment by RiedleroD** [comment]
I see, then I'll create a bug report in kate.
