### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by iandoug** [alerque/libertinus#501]
Hi

It's been a while. :-)

Is there an ETA for the next release?

Thanks, Ian

**Comment by alerque** [comment]
Sorry I've king of had all font related stuff on a back burner for a number of months. I'll try to catch up and take stock of where this is at these days and what the next release should be. I know there are some PRs I haven't even gotten to check out yet myself.

**Comment by iandoug** [comment]
Bump... :-)

**Comment by alerque** [comment]
Self bump! Yikes.

**Comment by iandoug** [comment]
Bump... :-)

**Comment by istathar** [comment]
Bump... :-)

**Comment by alerque** [comment]
On it. I finally got some things squared away so Fontship is up to date and this font builds with it. The biggest blocker has been things haven't been building with current python-fonttools, but I think I have that squared away.

**Comment by alerque** [comment]
https://github.com/alerque/libertinus/releases/tag/v7.050

**Comment by iandoug** [comment]
Thanks :-)
