### ISSUE TITLE
broken underbrace/overbrace when mathtools is used after libertinus

### ISSUE THREAD

**Issue by tpapp** [alerque/libertinus#507]
(I reported this issue originally at latex3/mathtools#43, and was told that this isn't a bug with `mathtools`.)

MWE:
```latex
\documentclass[a4paper]{article}
\usepackage{libertinus}         % using mathtools BEFORE works fine
\usepackage{fontspec}
\setmathfont{Latin Modern Math}
\usepackage{mathtools}
\begin{document}
\begin{equation}
  \underbrace{g_u \lambda_u \Gamma_u}_{\text{example}} = 
    \underbrace{\int g_e(\varphi) \delta(\varphi) d\varphi}_{\text{example}}
\end{equation}
\end{document}
```
results in 
![mathtools](https://user-images.githubusercontent.com/84122/170270565-565e76d9-abf3-4121-80a0-994c132b3b03.png)

using TeXLive 2021.20220204-1 in Ubuntu 22.04. Exchanging the order of `libertinus` and `mathtools` fixes the issue.

**Comment by khaledhosny** [comment]
It is not a font bug either. The issue you are linking to is saying it is a _document bug_ so you have to fix your document. Furthermore, this repository maintains only the OpenType fonts, the LaTeX package you are using is maintained elsewhere.

**Comment by hvoss49** [comment]
The problem is amsmath, which be loaded _always_ before unicode-math. In your case it is loaded by mathtools,
so it overrides some math definitions of unicode-math, which is loaded by libertinus-otf. Use:

```
\documentclass[a4paper]{article}
\usepackage{mathtools}
\usepackage{libertinus}   
\setmathfont{Latin Modern Math}

\begin{document}
\begin{equation}
  \underbrace{g_u \lambda_u \Gamma_u}_{\text{example}} = 
    \underbrace{\int g_e(\varphi) \delta(\varphi) d\varphi}_{\text{example}}
\end{equation}
\end{document}
```
