### ISSUE TITLE
[Feature Request] Math bold greek

### ISSUE THREAD

**Issue by Firestar-Reimu** [alerque/libertinus#510]
```
% this cannot display Math bold greek
\usepackage[math=+ss08]{libertinus}
\usepackage{bm}
\renewcommand\mathbf\bm
```

```
% this can display Math bold greek
% \usepackage[no-math]{fontspec}
% \setmainfont{Libertinus Serif}
% \setsansfont{Libertinus Sans}
% \usepackage[bold-style=ISO,sans-style=italic]{unicode-math}
% \setmathfont{Libertinus Math}[RawFeature={+ss08}]
```

test: `\[ \mathbf{\Phi} \]`

**Comment by hvoss49** [comment]
This works (lualatex):

```
\documentclass[a4paper]{article}
\usepackage[bold-style=ISO,sans-style=italic]{unicode-math}
\usepackage{libertinus}
\begin{document}

test: \[ \Phi \symbf{\Phi} \]

\end{document}
```

**Comment by Firestar-Reimu** [comment]
I use xelatex

I know that unicode-math can display math bold greek, but **libertine-otf + bm** cannot. Does that mean math bold greek is not part of the math font?

**Comment by hvoss49** [comment]
The math font has only a regular version. `\mathbf` uses by default the text font whereas `\symbf` uses the math font. The bold math version is internally faked by using the embolden keyword.

**Comment by Firestar-Reimu** [comment]
so unicode-math use fake-bold too?

**Comment by hvoss49** [comment]
It depends to the font. There are only a handful math fonts with an own bold face. And nearly all are commercial ones. 
All other fonts needs the "AutoFakeBold"  of `unicode-math`; they have only the regular series.

**Comment by Firestar-Reimu** [comment]
so do you have the plan of making a bold-italic math font?

**Comment by hvoss49** [comment]
Why?  AutoFakeBold  does it all ...
