### ISSUE TITLE
Compatibility between Regular and Bold versions in Libertinus Serif family

### ISSUE THREAD

**Issue by StefanPeev** [alerque/libertinus#514]
There isn't compatibility between Regular and Bold versions in Libertinus Serif family. For example see the pictures below:

![LibertinusSerif_01](https://user-images.githubusercontent.com/12949369/188317656-54cca400-1493-4da1-bb38-b566882766e2.jpg)
![LibertinusSerif_02](https://user-images.githubusercontent.com/12949369/188317659-0240a70a-d072-4d8c-aa26-2fcba15ec66f.jpg)
![LibertinusSerif_03](https://user-images.githubusercontent.com/12949369/188317660-98beb83d-7942-4f44-80af-97214f926e0b.jpg)
![LibertinusSerif_04](https://user-images.githubusercontent.com/12949369/188317662-458abac9-b5a0-4fbb-bbc0-7c2248feb567.jpg)

It means that it is impossible to create interpolation for Medium and SemiBold versions. I'm trying to solve this problem and after 18th September I'll offer my first results.

**Comment by StefanPeev** [comment]
The source files of Libertinus Serif v.7.042 (Regular, Medium, SemiBold, Bold) in UFO and VFC format are at the branch [CYRILLIC](https://github.com/StefanPeev/libertinus/tree/cyrillic/sources). The four styles are fully compatible.

**Comment by waldyrious** [comment]
For additional context regarding the closure of this issue, see https://github.com/alerque/libertinus/issues/524#issuecomment-1415495097:

> I closed pull request #520 and I'll close also all updates on Libertinus Serif. The reason is that I started a project [Common Serif](https://github.com/StefanPeev/Common-Serif) which is further development of Libertinus Serif but with a lot of changes. The aim of the project is to create masters (Regular and Bold, Italic and Bold Italic), which to be compatible and by which we to have a chance to generate instances like this (Regular, Medium, SemiBold, Bold; Italic, Medium Italic, SemiBold Italic, Bold Italic). All this means a serious changes in the project, it is why I think we need a new start. If you like the idea, please, give your notices on [Common Serif](https://github.com/StefanPeev/Common-Serif) repo.
