### ISSUE TITLE
Two very different appearances of the letter “J”

### ISSUE THREAD

**Issue by Ransom77** [alerque/libertinus#523]
Hello,

the italic variant of the letter (resp. the majuscule) “J”, differs very much from the regular variant. While the regular variant has no “head” at all resp. only a serif, the italic variant has a curved head and additionally a middle stroke (looks like a handwritten J). The italic variant differs so much from the regular variant that one has the impression that this letter does not belong to the font at all.

Greetings
Ransom

**Comment by waldyrious** [comment]
This has been raised before; please see the discussion at #98, and the associated PR #138.

I'll close this as a duplicate, but although #98 is also closed, feel free to comment there if you would like to propose a different resolution. I happen to [agree](https://github.com/alerque/libertinus/issues/98#issuecomment-371802146) with you (I'd put the "swashy" J as the alternate and the regular one as the main glyph in the italic variant, as is already the case in the upright variant), but the rest of the contributors would have to agree for this to be changed.

**Comment by Ransom77** [comment]
I have currently left a comment [here](https://github.com/alerque/libertinus/issues/98#issuecomment-1353341152).
