### ISSUE TITLE
Does Libertinus Mono contain the same special characters as Serif/Sans?

### ISSUE THREAD

**Issue by jchwenger** [alerque/libertinus#529]
**Describe the bug**
I am trying to render documents in svg using Cairo in Python with Libertinus Mono as the font, and some characters do not render. 

![Screenshot from 2023-03-19 14-15-51](https://user-images.githubusercontent.com/34098722/226182252-2d986789-bf14-4301-8969-8f27f8d82e65.png)

Here are examples of the kind of text that causes the problem:

```
hanoï, nà sản, cao bằng, diên biên phu
lạng sơn, quảng ninh, cao bằng
thích quảng đức,
```
Oddly enough, most of this works fine if I past this into LibreOffice and select Libertinus Mono (đức has an issue with the glyph, I assume, supposed to be to the right of the 'u' being displayed at the top of the c). 

This works all fine with Serif and Sans, and that left me a bit perplex with regard to the discrepancy between LibreOffice and Cairo, but now that I'm thinking about it and examining my document, it might be that LO just uses a fallback.

Is it a difficult thing to integrate new glyphs like that in the mono font? I'm looking for one that would have this potential to display many characters.

This is actually more like a feature request, but in any case thanks in advance for reading!

**Comment by kimmus** [comment]
The answer to your question is evident from your example.
Some monospaced fonts that include the characters in your example text are Consolas, FreeMono, Liberation Mono, Noto Mono, Noto Sans Mono (many fonts), Source Code Pro. There are certainly others—those are only the ones I happen to have.

**Comment by jchwenger** [comment]
Yes, you're right, thanks for taking the time to reply! In the end I created a workaround where I use the serif version, displaying the text letter by letter to simulate the mono effect. It would be lovely to have more characters in Libertinus Mono, but I'm sure this would require a lot of design work! Beautiful font family, I'm loving it!
