### ISSUE TITLE
Would it be doable to create a variant?

### ISSUE THREAD

**Issue by gctwnl** [alerque/libertinus#540]
I would love a variant where the lowercase characters of Sans are slightly larger as a height percentage of the uppercase characters, more close to how Optima looks. Would creating that be doable (i.e. do you have to change all the glyphs or are there more generic things you can do?

**Comment by alerque** [comment]
This would be doable of course, but it would take quite a bit of work. The outlines for this font are not parameterized (as they sometimes are for well made variable fonts with multiple axis) in such a way that this could be automated in any reasonable fashion. It would be a mostly manual process ... you would setup some guides for where you wanted the x-height to land then go through each glyph and adjust the outlines. This would be much trickier to do cleanly for the Italic faces than the uprights. Doable of course just a bit of work.

I have no plans to do this, but if anybody want it bad enough to tackle it themselves we could certainly consider integrating it as a stylistic alternate or OpenType variation axis.
