### ISSUE TITLE
Enable ss01 by default for certain languages

### ISSUE THREAD

**Issue by BrillanNording** [alerque/libertinus#546]
When Libertinus was originally forked from Libertine (version 6.0), what once constituted ss01 became the default glyphs for Ä, Ö, and Ü, while the original defaults in turn became the new ss01, with the reasoning being that the new default follows a “more conventional” form. In reality however, neither form is more conventional universally; it depends entirely on the function that the two dots serve. When serving as _diaeresis_, the new default is entirely reasonable. When indicating _umlaut_ on the other hand, having the dots closer to the letter is more sensible, which is the reason why this was the default in Libertine to begin with (please see [this page](https://libertine-fonts.org/smart/)). Furthermore, some languages (including my native tongue of Swedish) have these glyphs as separate letters entirely. While I cannot speak for every language, the old default felt a lot more natural when typesetting Swedish.

For this reason, I suggest enabling ss01 by default for German and Swedish at the very least, just as ss07 already is for Swedish (changing the shape of Ŋ). It might also be worth considering doing this for all languages which use Ä, Ö, and Ü for umlaut or as separate letters instead of diaereses. If I am not mistaken, this would include at least the Nordic, Uralic, and Turkic languages.

**Comment by alerque** [comment]
This makes sense to me, I'd be happy to consider it as a contribution. On a quick glance I don't see where ss07 is being enabled by default for Swedish, but presumably copying that would be the place to start.

Is the current `ss01` feature well implemented across all the styles (as in will changing this result in a consistent look across faces or are only some of them supported)?

**Comment by khaledhosny** [comment]
The default was swapped for German intentionally (https://github.com/alerque/libertinus/commit/467d782d67705560ba3ebcfa23d2698df1ca747f) because even German speakers found the “bunny-ear” diacritics unusual.

**Comment by alerque** [comment]
What Khaled said checks out. Given several comments I found about *not* liking those as the defaults (including about Linux Libertine) I think it would be better to leave well enough alone. They are of course available as `ss01` and we're not removing them, just not making them the default. Some people clearly did like that feature in the Libertine days, but some people used that as justification for *not* liking the font too. We can't have it both ways, and as it's been quite a few years now with this default I think we'll just keep it.
