### ISSUE TITLE
Request to Reduce Kerning Between `j` and `l` in Libertinus Mono font for Better LaTeX Representation

### ISSUE THREAD

**Issue by singularitti** [alerque/libertinus#554]
I am a Julia package developer and frequently document my work using LaTeX. I've encountered an issue with the Libertinus Mono font, particularly when typesetting Julia file extensions (`.jl`) using `\texttt{}`. The kerning between the letters `j` and `l` appears larger than ideal, which affects the presentation of file names in my LaTeX documents.

Could you please consider reducing the kerning between these two characters in the Libertinus Mono font? This adjustment would improve the clarity and visual representation of `.jl` extensions in technical documents.

Below is a Minimal Working Example (MWE) illustrating the issue:

```latex
\documentclass{article}
\usepackage{libertinus}
\begin{document}
\texttt{example.jl} jl \textbf{jl}
\end{document}
```

<img width="305" alt="image" src="https://github.com/alerque/libertinus/assets/25192197/cb5b8990-2ece-4efb-a760-e9161d324392">

Thank you for your attention to this matter and for your contributions to the Libertinus font family.

**Comment by kimmus** [comment]
How can you have kerning in a monospaced font?

**Comment by singularitti** [comment]
Forgive my words... I mean the spacing between `j` and `l`. Is that possible?

**Comment by kimmus** [comment]
Only by shifting j and/or 1 within the space allotted to them, which is the same for every character in the font. Such an adjustment would affect the spacing of every other combination with the adjusted character(s).—I’m not a font designer, I just follow these discussions because I use the font. But I know that monospaced fonts are quite inflexible.

**Comment by waldyrious** [comment]
> Only by shifting j and/or l within the space allotted to them, which is the same for every character in the font. Such an adjustment would affect the spacing of every other combination with the adjusted character(s).

For the record, that's precisely the principle behind the technique used in the Monaspace font, which they call "texture healing". It's described in [this document](https://github.com/githubnext/monaspace/blob/main/docs/Texture%20Healing.md) and in the [project's website](https://monaspace.githubnext.com/), but here's an image demonstrating the effect (note the changes in the `l`, the `m` and the `i`):

![image](https://github.com/alerque/libertinus/assets/478237/437b6b56-c8c6-4eb8-9ac1-bd517712543e)

**Comment by singularitti** [comment]
Thanks for replying @waldyrious! Does Libertinus support or will support this feature?

**Comment by waldyrious** [comment]
As far as I am aware, there are no plans to implement this. I just thought I'd mention the technique here in case it helps address this issue.

**Comment by alerque** [comment]
The technique used by Monaspace uses an assortment of alternative glyph shapes and substitution for sequences where narrow, normal, and wide characters appear to the right/left of each-other. It's clever and looks great, but it is also a massive undertaking. I'd be happy to facilitate contributions if somebody wanted to tackle a system like that for this font, but there is no realistic possibility that I'll get around to it any time soon. If I did have a bunch of time I'd much rather work on normalizing the weights so they could be used as masters in a variable font.

As mentioned already kerning is out of the question for monospace fonts, and complex sequences of substitution as would be required to address this one use case (without catching other false positives like `jlre`) are out of the question as one-off fixes. We either need to address all/most of the possibilities or just let it alone and be a normal monospace font.

I'm going to close this as there is no practical way or plan to address this, but if anybody wants to open an issue for a "texture healing" like system I'd be happy for it to sit around as a feature request in case somebody comes along and wants to work on it.
